language: go
os:
  - linux
  - osx
go:
  - '1.10'
before_install:
  - mkdir -p "${GOPATH}/bin"
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure
script:
  - ./test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
